<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>TimeSheet.Modules.EmploymentManagement.Infrastructure</AssemblyName>
    <RootNamespace>TimeSheet.Modules.EmploymentManagement.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeSheet.Modules.EmploymentManagement.Application\TimeSheet.Modules.EmploymentManagement.Application.csproj" />
    <ProjectReference Include="..\TimeSheet.Modules.EmploymentManagement.Domain\TimeSheet.Modules.EmploymentManagement.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
